print("x:")
x = int(input())
print("*a:")
a = int(input())
print("/b:")
b = int(input())
print("+c:")
c = int(input())
print("-d:")
d = int(input())
print(str(x) + " * " + str(a) + " / " + str(b) + " + " + str(c) + " - " + str(d)+ " = ", end = '')
print(x*a/b+c-d)